services:
  db_upprpo:
    image: postgres:15
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my-network
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5
  migrations:
    build:
      context: ./backend/src/api
      dockerfile: Dockerfile
    command: alembic upgrade head
    env_file:
      - ./.env
    networks:
      - my-network
    depends_on:
      db_upprpo:
        condition: service_healthy
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - my-network
    command: redis-server --appendonly yes
    volumes:
      - "redis_data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  backend_upprpo:
    build:
      context: ./backend/src/api
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src/api/uploads:/app/uploads
    networks:
      - my-network
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    restart: on-failure
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      BOT_UPLOADS_DIR: /app/uploads/pins
    volumes:
      - ./backend/src/api/uploads:/app/uploads
    networks:
      - my-network
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: on-failure

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_dist:/app/dist
    environment:
      - NPM_CONFIG_REGISTRY=https://registry.npmmirror.com
    command: sh -c "npm ci && npm run build"
    restart: "no"
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      # - ./certs:/etc/nginx/certs:ro # Для SSL в будущем
    depends_on:
      - frontend
      - backend_upprpo
    networks:
      - my-network
    restart: always

volumes:
  db_data:
  redis_data:
  frontend_dist:

networks:
  my-network:
    driver: bridge
