"""update User

Revision ID: f24ce040a43f
Revises: a5c3063ba1d8
Create Date: 2026-04-18 00:39:44.479503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24ce040a43f'
down_revision: Union[str, Sequence[str], None] = 'a5c3063ba1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_users', sa.Column('description', sa.String(), nullable=True))
    op.add_column('web_users', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_users', 'img_url')
    op.drop_column('web_users', 'description')
    # ### end Alembic commands ###
